baseurl = "/"
title = "YUQI LIAO"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-127483222-1"

# Ignore certain files as recommended
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

#enable emoji in content rmd files (https://www.webfx.com/tools/emoji-cheat-sheet/)
enableEmoji = true

# Other settings
hasCJKLanguage = true
relativeurls = true


[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Describe your website"
  copyright = "&copy;Yuqi Liao - 2019"
  sidebarAbout = [
    "I am a creative illustrator and graphic designer with more than 10 years of experience.",
    "Originally from Toronto, currently based in London.::smile::😀"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "yuqi.liao@georgetown.edu"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Post"
  url = "post/"
  
  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  #facebook      = "full page or profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  email         = "yuqi.liao@georgetown.edu"
  twitter       = "https://twitter.com/YuqiLiao"
  linkedin      = "https://www.linkedin.com/in/yuqiliao/"
  #stackoverflow = "full profile url in stackoverflow"
  instagram     = "https://www.instagram.com/yuqi.liao/"
  github        = "https://github.com/yuqiliao"
  #youtube       = "full profile url in youtube"
  #whatsapp      = "wa.me service link"
  

